Добавлена обработка SNAPSHOT-версий
EvilBeaver/os-hub-frontend pull request #33
Opened 2021-09-20 11:31 UTC by nixel2007

Если версия пушится в канал, отличный от stable (например, dev), вместо данных о версии записываются данные о SNAPSHOT-версии

2021-09-20 11:36 UTC, theshadowco approved these changes

2021-09-20 12:33 UTC, EvilBeaver commented
ммм.. а зойчем это?

2021-09-20 12:52 UTC, nixel2007 commented
@EvilBeaver чтобы VA пушить прямо с девелопа, не дожидаясь релиза

2021-09-20 13:01 UTC, EvilBeaver requested changes

2021-09-20 13:01 UTC, EvilBeaver commented on src/model/Modules/ОбщегоНазначения.os
> +	ПутьКФайлу = ОбъединитьПути(ПутьККаталогуПакета, ИмяФайла);
Тут точно не ломаем ничего? Почему запись вне условия? Мы не пишем два раза файл, если это НЕ ТестоваяВерсия?

2021-09-20 13:08 UTC, nixel2007 commented on src/model/Modules/ОбщегоНазначения.os
> +	ПутьКФайлу = ОбъединитьПути(ПутьККаталогуПакета, ИмяФайла);
Нет, не пишем. В имени файла по умолчанию содержится имя пакета + номер версии. выше по коду, для НЕтестовых версий файл дополнительно записывается без номера версии (чтобы сделать "последнюю" версию)

2022-05-16 08:45 UTC, nixel2007 commented on src/model/Modules/ОбщегоНазначения.os
> +		ИмяФайла = СтрШаблон("%1-SNAPSHOT.ospx", ОписаниеПакета.Идентификатор);
Готово.

2022-05-16 08:48 UTC, EvilBeaver approved these changes

2022-05-16 08:49 UTC, merged